<?php
/** Контент кейса «Telegram-ассистент» (EN/UK/RU). Доказательство = скрины из бота. wp eval-file */
$cases = ['en' => 122, 'uk' => 123, 'ru' => 124];
$REPO  = 'https://github.com/vasutenko26/portfolio/tree/main/assistant';

$C = [];
$C['en'] = [
  'summary' => 'A self-hosted Telegram task assistant for two people. Natural-language and voice input; Gemini breaks each task into subtasks, sets priority and deadline. Collaboration with accept/decline, comments and reminders. Runs in Docker on my own server; backed up 3× a day.',
  'result_metric' => 'Gemini · Docker · self-hosted · 3× daily backup',
  'stack' => 'Python, python-telegram-bot, Gemini, SQLite, Docker, Caddy, cron',
  'task' => '<p>My partner and I needed one shared place to set tasks for each other — with deadlines, accountability and a nudge when something slips. No SaaS subscription, no third-party server holding our data, and as little friction as possible when capturing a task.</p>',
  'approach' => '<p><strong>A real bot, not a script:</strong> a Telegram bot in <strong>Python</strong> (<code>python-telegram-bot</code>, long-polling, no public port) with <strong>SQLite</strong> for durable state, packaged in <strong>Docker</strong> on the same hardened server as the rest of the stack.</p><p><strong>AI where it removes friction:</strong> you type or <strong>dictate</strong> a task in plain language («call the client tomorrow at 3pm, urgent») and <strong>Gemini</strong> extracts the title, <strong>priority and deadline</strong>, and splits it into 3–6 subtasks with short advice. Gemini also writes a morning plan-of-the-day and a weekly review.</p><p><strong>Built for two:</strong> assign a task to your partner — they <strong>accept / clarify / decline</strong>; per-task comment thread, file attachments, pings, and a notification (with comment) the moment work is done. A shared <strong>dashboard</strong> shows both people’s open tasks and a completed log by period.</p><p><strong>It keeps you honest:</strong> smart reminders (a day before, an hour before, then escalation with an auto-nudge on overdue), a 09:30 digest, priorities, tags, recurring tasks, points &amp; streaks, PNG charts and CSV export.</p><p><strong>Operations in one hand:</strong> the database is <strong>backed up three times a day</strong> to a separate “server” bot (DB dumps + media + configs + a full archive, split under Telegram’s 50&nbsp;MB limit, newest-only on disk); all infra alerts (failures, health, Grafana) go to that same technical bot.</p>',
  'result' => '<p>A daily driver that actually gets used: tasks captured in seconds by voice or text, broken down by AI, and nothing quietly forgotten. The screenshots below are straight from the live bot — menu, AI breakdown, dashboard, plan-of-the-day, progress with charts, and partner hand-off. <strong>Self-hosted, AI-assisted, backed up, and run end to end by one engineer.</strong> Source is in the repo.</p>',
];
$C['ru'] = [
  'summary' => 'Self-hosted Telegram-ассистент задач на двоих. Ввод текстом и голосом; Gemini разбивает задачу на подзадачи, ставит приоритет и дедлайн. Совместная работа с приёмкой, комментариями и напоминаниями. Работает в Docker на своём сервере; бэкап 3 раза в день.',
  'result_metric' => 'Gemini · Docker · self-hosted · бэкап 3×/день',
  'stack' => 'Python, python-telegram-bot, Gemini, SQLite, Docker, Caddy, cron',
  'task' => '<p>Нам с напарником нужно было одно общее место, чтобы ставить друг другу задачи — с дедлайнами, ответственностью и пинком, когда что-то проседает. Без SaaS-подписки, без чужого сервера с нашими данными и с минимумом трения при создании задачи.</p>',
  'approach' => '<p><strong>Полноценный бот, а не скрипт:</strong> Telegram-бот на <strong>Python</strong> (<code>python-telegram-bot</code>, long-polling, без публичного порта) с <strong>SQLite</strong> для устойчивого состояния, в <strong>Docker</strong> на том же захардненном сервере, что и весь стек.</p><p><strong>AI там, где убирает трение:</strong> пишешь или <strong>надиктовываешь</strong> задачу обычным языком («созвон с клиентом завтра в 15:00, срочно») — <strong>Gemini</strong> сам вытаскивает заголовок, <strong>приоритет и дедлайн</strong> и делит на 3–6 подзадач с короткими советами. Gemini же пишет утренний план дня и недельное ревью.</p><p><strong>Сделано на двоих:</strong> поручаешь задачу напарнику — он <strong>принимает / уточняет / отклоняет</strong>; тред-комментарии, вложения, пинги и уведомление (с комментарием) в момент выполнения. Общий <strong>дашборд</strong> показывает открытые задачи обоих и журнал выполненного за период.</p><p><strong>Держит в тонусе:</strong> умные напоминания (за день, за час, затем эскалация с авто-«подзатыльником» при просрочке), дайджест в 09:30, приоритеты, теги, повторяющиеся задачи, очки и стрики, графики PNG и экспорт CSV.</p><p><strong>Эксплуатация в одних руках:</strong> база <strong>бэкапится трижды в день</strong> в отдельного «серверного» бота (дампы БД + медиа + конфиги + полный архив, дробление под лимит Telegram 50&nbsp;МБ, на диске только свежее); вся техничка (сбои, health, Grafana) — туда же.</p>',
  'result' => '<p>Рабочий инструмент на каждый день: задача заводится за секунды голосом или текстом, разбивается AI, и ничего тихо не теряется. Скрины ниже — прямо из живого бота: меню, AI-разбивка, дашборд, план дня, прогресс с графиком и передача задачи напарнику. <strong>Self-hosted, с AI, с бэкапами, и всё это от и до сделал один инженер.</strong> Исходник — в репозитории.</p>',
];
$C['uk'] = [
  'summary' => 'Self-hosted Telegram-асистент задач на двох. Введення текстом і голосом; Gemini розбиває задачу на підзадачі, ставить пріоритет і дедлайн. Спільна робота з прийманням, коментарями та нагадуваннями. Працює в Docker на власному сервері; бекап 3 рази на день.',
  'result_metric' => 'Gemini · Docker · self-hosted · бекап 3×/день',
  'stack' => 'Python, python-telegram-bot, Gemini, SQLite, Docker, Caddy, cron',
  'task' => '<p>Нам із напарником потрібне було одне спільне місце, щоб ставити одне одному задачі — з дедлайнами, відповідальністю та поштовхом, коли щось провисає. Без SaaS-підписки, без чужого сервера з нашими даними та з мінімумом тертя під час створення задачі.</p>',
  'approach' => '<p><strong>Повноцінний бот, а не скрипт:</strong> Telegram-бот на <strong>Python</strong> (<code>python-telegram-bot</code>, long-polling, без публічного порту) із <strong>SQLite</strong> для стійкого стану, у <strong>Docker</strong> на тому ж захардненому сервері, що й увесь стек.</p><p><strong>AI там, де прибирає тертя:</strong> пишеш або <strong>надиктовуєш</strong> задачу звичайною мовою («дзвінок клієнту завтра о 15:00, терміново») — <strong>Gemini</strong> сам дістає заголовок, <strong>пріоритет і дедлайн</strong> та ділить на 3–6 підзадач із короткими порадами. Gemini ж пише ранковий план дня та тижневе ревʼю.</p><p><strong>Зроблено на двох:</strong> доручаєш задачу напарнику — він <strong>приймає / уточнює / відхиляє</strong>; тред-коментарі, вкладення, пінги та сповіщення (з коментарем) у мить виконання. Спільний <strong>дашборд</strong> показує відкриті задачі обох і журнал виконаного за період.</p><p><strong>Тримає в тонусі:</strong> розумні нагадування (за день, за годину, далі ескалація з авто-«потиличником» при простроченні), дайджест о 09:30, пріоритети, теги, повторювані задачі, очки та стріки, графіки PNG і експорт CSV.</p><p><strong>Експлуатація в одних руках:</strong> база <strong>бекапиться тричі на день</strong> до окремого «серверного» бота (дампи БД + медіа + конфіги + повний архів, дроблення під ліміт Telegram 50&nbsp;МБ, на диску лише свіже); уся технічка (збої, health, Grafana) — туди ж.</p>',
  'result' => '<p>Робочий інструмент на щодень: задача заводиться за секунди голосом чи текстом, розбивається AI, і ніщо тихо не губиться. Скрини нижче — просто з живого бота: меню, AI-розбивка, дашборд, план дня, прогрес із графіком та передача задачі напарнику. <strong>Self-hosted, з AI, із бекапами, і все це від і до зробив один інженер.</strong> Вихідник — у репозиторії.</p>',
];

$keys = ['summary' => 'f_sum', 'result_metric' => 'f_metric', 'stack' => 'f_stack',
         'task' => 'f_task', 'approach' => 'f_appr', 'result' => 'f_res'];
foreach ($cases as $lang => $id) {
    foreach ($C[$lang] as $field => $val) {
        update_post_meta($id, $field, $val);
        update_post_meta($id, '_' . $field, $keys[$field]);
    }
    update_post_meta($id, 'repo_url', $REPO);
    update_post_meta($id, '_repo_url', 'f_repo');
    echo "bot case $lang (#$id) updated\n";
}
